# Generated by Django 2.2.5 on 2019-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default='no_series', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
